//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class activities
    {
        public int activities_id { get; set; }
        public int activities_event { get; set; }
        public string activities_name { get; set; }
        public int activities_day { get; set; }
        public System.TimeSpan activities_start_time { get; set; }
        public Nullable<int> activities_moderator { get; set; }
        public Nullable<int> activities_jury { get; set; }
    
        public virtual jury_list jury_list { get; set; }
        public virtual moderators moderators { get; set; }
    }
}
