//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public events()
        {
            this.moderators = new HashSet<moderators>();
        }
    
        public int events_id { get; set; }
        public string events_name { get; set; }
        public System.DateTime events_date { get; set; }
        public int events_days { get; set; }
        public int events_city { get; set; }
        public Nullable<int> events_winner { get; set; }
        public Nullable<int> events_direction { get; set; }
        public string events_img { get; set; }
    
        public virtual cities cities { get; set; }
        public virtual member member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moderators> moderators { get; set; }
        public virtual directions directions { get; set; }
    }
}
