//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class jury_list
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jury_list()
        {
            this.activities = new HashSet<activities>();
        }
    
        public int jury_list_id { get; set; }
        public Nullable<int> jury1 { get; set; }
        public Nullable<int> jury2 { get; set; }
        public Nullable<int> jury3 { get; set; }
        public Nullable<int> jury4 { get; set; }
        public Nullable<int> jury5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activities> activities { get; set; }
        public virtual jury jury { get; set; }
        public virtual jury jury6 { get; set; }
        public virtual jury jury7 { get; set; }
        public virtual jury jury8 { get; set; }
        public virtual jury jury9 { get; set; }
    }
}
