//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class jury
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jury()
        {
            this.jury_list = new HashSet<jury_list>();
            this.jury_list1 = new HashSet<jury_list>();
            this.jury_list2 = new HashSet<jury_list>();
            this.jury_list3 = new HashSet<jury_list>();
            this.jury_list4 = new HashSet<jury_list>();
        }
    
        public int jury_id { get; set; }
        public string jury_name { get; set; }
        public string jury_gender { get; set; }
        public string jury_mail { get; set; }
        public System.DateTime jury_bd { get; set; }
        public int jury_country { get; set; }
        public string jury_phone { get; set; }
        public int jury_direction { get; set; }
        public string jury_password { get; set; }
        public string jury_photo { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual directions directions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jury_list> jury_list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jury_list> jury_list1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jury_list> jury_list2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jury_list> jury_list3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jury_list> jury_list4 { get; set; }
    }
}
