//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class moderators
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public moderators()
        {
            this.activities = new HashSet<activities>();
        }
    
        public int moderators_id { get; set; }
        public string moderators_name { get; set; }
        public string moderators_gender { get; set; }
        public string moderators_mail { get; set; }
        public System.DateTime moderators_bd { get; set; }
        public int moderators_country { get; set; }
        public string moderators_phone { get; set; }
        public int moderators_direction { get; set; }
        public int moderators_event { get; set; }
        public string moderators_password { get; set; }
        public string moderators_photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activities> activities { get; set; }
        public virtual countries countries { get; set; }
        public virtual directions directions { get; set; }
        public virtual events events { get; set; }
    }
}
