//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class infoEntities : DbContext
    {
        public infoEntities()
            : base("name=infoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activities> activities { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<directions> directions { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<jury> jury { get; set; }
        public virtual DbSet<jury_list> jury_list { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<moderators> moderators { get; set; }
        public virtual DbSet<organizers> organizers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
