//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizers
    {
        public int organizers_id { get; set; }
        public string organizers_name { get; set; }
        public string organizers_mail { get; set; }
        public System.DateTime organizers_bd { get; set; }
        public int organizers_country { get; set; }
        public string organizers_phone { get; set; }
        public string organizers_password { get; set; }
        public string organizers_photo { get; set; }
        public string organizers_gender { get; set; }
    
        public virtual countries countries { get; set; }
    }
}
